name: surrealdartb
description: Dart FFI bindings for SurrealDB with native Rust integration
version: 0.0.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  build: ^2.4.0
  source_gen: ^2.0.0
  analyzer: ^7.0.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  hooks: ^0.20.4
  build_runner: ^2.4.0
  native_toolchain_rs:
    git:
      url: https://github.com/GregoryConrad/native_toolchain_rs
      ref: 34fc6155224d844f70b3fc631fb0b0049c4d51c6
      path: native_toolchain_rs
